explore/urls.py
from django.urls import path
from . import views

app_name = 'explore'

urlpatterns = [
        path('', views.home, name='home'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home')
]

ongaku_website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('explore/', include('explore.urls')),
    path('reviews/', include('reviews.urls', namespace='reviews')),
    path('admin/', admin.site.urls),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
        path('', views.crear_reseña, name='crear_reseña'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
        #path('list/', views.show_users, name='list_of_users'), 
        path('registro/', views.registro, name='registro'),
        path('ingreso/', views.ingreso, name='ingreso'),
        path('salir/', views.salir, name='salir'),
        path('<str:username>/', views.mostrar_perfil, name='perfil'),
        ]

explore/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

reviews/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Review(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now_add=True)
    artista = models.CharField(max_length=100)
    album = models.CharField(max_length=100)
    contenido = models.TextField()
    canción_fav = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.usuario} - {self.artista} - {self.album}"

users/models.py
from django.db import models

# Create your models here.



    

reviews/forms.py
from django import forms
from .models import Review

class FormularioReseña(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['artista', 'album', 'contenido', 'canción_fav',]

users/forms.py
#Esto es para el formulario de crear cuenta.
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# Esto es para el formulario de inicio de sesión.
from django.contrib.auth.forms import AuthenticationForm

class RegistroFormulario(UserCreationForm):
    username = forms.CharField(label="Nombre de usuario",)
    password1 = forms.CharField(label="Contraseña")
    password2 = forms.CharField(label="Repite la contraseña")
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

explore/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, "explorar.html")

home/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader
from django.views.decorators.cache import never_cache

# Create your views here.
@never_cache
def home(request):
    return render(request, 'home.html', {'usrname': request.user.username})

reviews/views.py
from django.shortcuts import render, redirect
from .forms import FormularioReseña

def crear_reseña(request):
    if not request.user.is_authenticated:
            mensaje = "Debes iniciar sesión para crear una reseña."
            return render(request, "no_autenticado.html", {"mensaje": mensaje})
    if request.method == 'POST':
        form = FormularioReseña(request.POST)
        if form.is_valid():
            # Crea el objeto pero no lo guarda
            reseña = form.save(commit=False) 
            # Asigna el usuario que hace la reseña
            reseña.usuario = request.user      
            reseña.save()                      
            return redirect('users:perfil', username=request.user.username)
    else:
        form = FormularioReseña()
    return render(request, 'reseñar.html', {'form': form})

users/views.py
from django.template import loader
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import RegistroFormulario
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate
from django.contrib.auth import logout
from django.contrib.auth.models import User
from reviews.models import Review
from django.shortcuts import get_object_or_404


def registro(request):
    if request.method == "POST":
        form = RegistroFormulario(request.POST)
        if form.is_valid():
            form.save()
            return redirect("home")
    else:
        form = RegistroFormulario()

    return render(request, "registrar.html", {"form": form}) 

def ingreso(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            # Autenticar al usuario
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)  # Iniciar sesión al usuario
                return redirect('explore:home') 
            else:
                form.add_error(None, 'Nombre de usuario o contraseña incorrecta.')
    else:
        form = AuthenticationForm()
    return render(request, 'ingresar.html', {'form': form})

def salir(request):
    logout(request)  # Cierra la sesión del usuario
    return redirect('explore:home')

def mostrar_perfil(request, username):
    usuario = get_object_or_404(User, username=username)
    reseñas = Review.objects.filter(usuario=usuario)
    return render(request, 'perfil.html', {'usuario': usuario, 'reseñas': reseñas})

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet", href="{% static 'base.css' %}">
    <title>
        {% block title %} {% endblock title %}
    </title>
</head>

<body>
<header>
    {# Si el usuario no ha iniciado sesión. #}
    {% if not user.is_authenticated %}
        <h1 id="website-logo"> <a href="{% url 'home' %}">Ongaku - 音楽</a></h1>
        <div id="container">
            <nav>
                <a href="{% url 'explore:home' %}">Explorar</a>
                <a href="{% url 'reviews:crear_reseña' %}">Reseñar</a>
            </nav>

            <nav>
                <a href="{% url 'users:registro' %}">Crear cuenta</a>
                <a href="{% url 'users:ingreso' %}">Iniciar sesión</a>
            </nav>
        </div>

        {# Si el usuario ya inició sesión. #}
        {% else %}
        <h1 id="website-logo"> <a href="{% url 'home' %}">Ongaku - 音楽</a></h1>
        <div id="container">
            <nav>
                <a href="{% url 'explore:home' %}">Explorar</a>
                <a href="{% url 'reviews:crear_reseña' %}">Reseñar</a>
            </nav>

            <nav>
                <a id="usrname" href="{% url 'users:perfil' username=user.username %}">{{user.username}}</a>
                <a href="{% url 'users:salir' %}">Salir</a>
            </nav>
        {% endif %}
</header>

<main>
{% block content %}
{% endblock content %}
</main>

<hr>

<footer>
<p> Nosotros<br> 
Redes sociales<br>
Información de contacto<br> 
© 2025 Ongaku</p>
</footer>
</body>
</html>

templates/explorar.html
{% extends "base.html" %}

{% block title %}
Ongaku | Explorar
{% endblock title %}

{% block content %}
Aquí se verán las reseñas más recientes proporcionadas por los usuarios de Ongaku.
{% endblock content %}

templates/explore.html
{% extends "base.html" %}

{% block title %}
Ongaku | Explorar
{% endblock title %}

{% block content %}
Aquí se verán las reseñas más recientes proporcionadas por los usuarios de Ongaku.
{% endblock content %}

templates/home.html
{% extends "base.html" %}
{% load static %}

{% block title %} Ongaku {% endblock title %}

{% block content %}
<h3> La música nos une. </h3>
<p> Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloribus iste assumenda molestiae officia sunt sint ex soluta similique. Velit tempore laudantium quos. Officia repellendus, quod aliquam beatae unde nostrum blanditiis! </p>
<br>
<img id="community" src="{% static 'mabe-fratti.jpg' %}"
alt="Imagen del homepage de Ongaku."
width="480"
height="259.5"
>
{% endblock content %}

templates/ingresar.html
{% extends "base.html" %}

{% block title %}
Ongaku | Iniciar sesión
{% endblock title %}

{% block content %}
<h3>¡Inicia sesión!</h3>
<form method="post" action={% url 'users:ingreso' %}>
    {% csrf_token %}
    {{ form.as_p }}
    <p>
        <button type="reset">Reiniciar</button>
        <button type="submit">Ingresar</button>
    </p> 
</form>
<p>¿Aún no tienes una cuenta? <a href="{% url 'users:registro' %}">Crea una cuenta aquí.</a></p>
{% endblock content %}

templates/list.html
{% extends "base.html" %}

{% block title %}
Ongaku | Usuarios
{% endblock title %}

{% block content%}
<div>
    <a href="{% url 'login' %}"> Iniciar sesión </a>
    <a href="{% url 'signup' %}"> Crear cuenta </a>
</div>

<br>

<h3>Usuarios registrados en Ongaku:</h3>

<br>

{# Aquí se deben enlistar los usuarios de la base de datos. #}
<ul>
    {% for user in users %}
    <li> <a> {{user.username}}</a> </li>
    {% endfor %}
</ul>
{% endblock content%}

templates/no_autenticado.html
{% extends 'base.html' %}

{% block content %}
<p>{{mensaje}}</p>
<a href="{% url 'users:ingreso' %}">Inicia sesión aquí.</a>
{% endblock content%}

templates/perfil.html
{% extends "base.html" %}

{% block title %}
Ongaku | Perfil
{% endblock title %}


{% block content %}
<h1>Perfil de {{ usuario.username }}</h1>

<ul>
  {% for reseña in reseñas %}
  <li>{{reseña.album}} de {{ reseña.artista }} — {{ reseña.contenido }}</li>
  {% empty %}
    <li>Este usuario no tiene reseñas todavía.</li>
  {% endfor %}
</ul>
{% endblock content %}

templates/registrar.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Ongaku | Crear cuenta
{% endblock title %}

{% block content %}

<h3> ¡Crea tu cuenta! </h3>

<form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <div>
        <button type="reset">Reiniciar</button>
        <button type="submit">Crear</button>
    </div>
</form>
<p>¿Ya tienes una cuenta? <a href="{% url 'users:ingreso' %}">Inicia sesión aquí.</a></p>
{% endblock content %}

templates/reseñar.html
{% extends "base.html" %}

{% block title %}
Ongaku | Reseñar
{% endblock title %}

{% block content %}
<div id="form">
<h1 id="msj">¡Cuéntanos qué piensas de ese álbum que has estado escuchando!</h1>
<form class="formulario" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Publicar reseña</button>
</form>
</div>
{% endblock content %}

templates/signup.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Ongaku | Crear cuenta
{% endblock title %}

{% block content %}

<h3> ¡Crea tu cuenta! </h3>

<form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <div>
        <input type="reset">
        <input type="submit">
    </div>
</form>
{% endblock content %}